import Head from "next/head";
import { useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import { getUser } from "../../redux/slices/userSlice";
import styles from "../../styles/Home.module.css";
import { ContainedButton, PrimaryButton } from "../components/atoms";
import ITyped from "../firebase/ityped";
import { emptyAnswers, getAnswers } from "../../redux/slices/answersSlice";
import Router from "next/router";
import { emptyQuestions } from "../../redux/slices/questionsSlice";

type HOME = {
  title: string;
  content1: string;
  content1_1: string;
  content2: string;
  content2_1: string;
};

export default function Home({
  title,
  content1,
  content1_1,
  content2,
  content2_1,
}: HOME) {
  const dispatch = useDispatch();
  const user = useSelector(getUser).user;
  const answers = useSelector(getAnswers).answers;

  useEffect(() => {
    dispatch(emptyAnswers());
    dispatch(emptyQuestions());
    console.log(user);
  }, []);

  const handleClick = () => {
    if (user.isSignedIn) {
      Router.push("/users/selectlanguage");
    } else {
      Router.push("/signin");
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-screen h-screen">
        <div className="h-1/6"></div>
        <div className="h-2/6 text-center text-5xl">
          <ITyped />
        </div>
        <div className="h-2/6 text-center font-mono text-2xl">
          {content2}
          <div className="mt-16">{content2_1}</div>
        </div>
        <div className="h-1/6">
          {user.uid ? (
            <div className="w-full text-center">
              <PrimaryButton label={"プレイ"} onClick={handleClick} />
            </div>
          ) : (
            <div className="w-full flex">
              <div className="w-1/2 text-center">
                <ContainedButton label={"今すぐプレイ"} href={"/guests/play"} />
              </div>
              <div className="w-1/2 text-center">
                <PrimaryButton label={"登録してプレイ"} onClick={handleClick} />
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

// ビルド時に実行される
export async function getStaticProps() {
  const title = "TyPro";
  const content1 = "Welcome to TyPro";
  const content1_1 = "プログラムのタイピングゲームです。";
  const content2 = "Skills you can learn";

  const content2_1 = "コードを打つのが早くなる いろんな言語を学べる ";

  return {
    props: {
      title,
      content1,
      content1_1,
      content2,
      content2_1,
    },
  };
}
