import Head from "next/head";
import { useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import { getUser } from "../../redux/slices/userSlice";
import styles from "../../styles/Home.module.css";
import {
  ContainedButton,
  DropdownIcon,
  PrimaryButton,
} from "../components/atoms";
import ITyped from "../firebase/ityped";
import { emptyAnswers, getAnswers } from "../../redux/slices/answersSlice";
import Router from "next/router";
import { emptyQuestions } from "../../redux/slices/questionsSlice";
import { IconButton } from "@material-ui/core";

type HOME = {
  title: string;
  content1: string;
  content1_1: string;
  content2: string;
  content2_1: string;
};

export default function Home({
  title,
  content1,
  content1_1,
  content2,
  content2_1,
}: HOME) {
  const dispatch = useDispatch();
  const user = useSelector(getUser).user;
  const answers = useSelector(getAnswers).answers;

  useEffect(() => {
    dispatch(emptyAnswers());
    dispatch(emptyQuestions());
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-screen h-screen">
        <div className="h-1/6 text-center text-5xl pt-16">
          <ITyped />
        </div>
        <div className="text-center font-mono text-2xl">
          <div className="pt-16 pb-4">{content2}</div>
          <div className="">{content2_1}</div>
        </div>
        <div className="">
          {user.isSignedIn ? (
            <div className="w-full flex pt-24">
              <div className="w-1/2 text-center">
                <ContainedButton
                  label={"プレイ"}
                  href={"/users/selectlanguage"}
                />
              </div>
              <div className="w-1/2 text-center">
                <ContainedButton
                  label={"協力プレイ"}
                  href={"/users/selectroom"}
                />
              </div>
            </div>
          ) : (
            <div className="w-full flex pt-24">
              <div className="w-1/2 text-center">
                <ContainedButton label={"今すぐプレイ"} href={"/guests/play"} />
              </div>
              <div className="w-1/2 text-center">
                <ContainedButton
                  label={"ログインしてプレイ"}
                  href={"/signin"}
                />
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

// ビルド時に実行される
export async function getStaticProps() {
  const title = "TyPro";
  const content1 = "Welcome to TyPro";
  const content1_1 = "プログラムのタイピングゲームです。";
  const content2 = "Skills you can learn";

  const content2_1 = "コードを打つのが早くなる いろんな言語を学べる ";

  return {
    props: {
      title,
      content1,
      content1_1,
      content2,
      content2_1,
    },
  };
}
